name: "Validate Flyway Migrations"
description: "Ensures Flyway migrations follow the correct sequence."
inputs:
  migration_dirs:
    description: "Path to the migration directory"
    required: false
    default: "src/main/resources/db/migrations"
  fixtures_dirs:
    description: "Path to the fixtures directory"
    required: false
    default: "src/main/resources/db/fixtures"
branding:
  icon: 'alert-triangle'
  color: 'red'
runs:
  using: "composite"
  steps:
    - name: Run Flyway Migration Check
      shell: bash
      env:
        MIGRATION_DIRS: ${{ inputs.migration_dirs }}
        FIXTURES_DIRS: ${{ inputs.fixtures_dirs }}
      run: |
        chmod +x ${{ github.action_path }}/validate_flyway_migrations.sh
        ${{ github.action_path }}/validate_flyway_migrations.sh